apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck-deployment
  labels:
    app: rundeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      containers:
      - name: rundeck
        image: rundeckpro/enterprise:4.3.1
        ports:
        - containerPort: 4440
        env:
          - name: RUNDECK_GRAILS_URL
            value: "http://192.168.49.2:30000"
          - name: RUNDECK_SERVER_ADDRESS
            value: "0.0.0.0"
---
apiVersion: v1 
kind: Service
metadata:
  name: rundeck-service
spec:
  selector:
    app: rundeck
  type:
    LoadBalancer
  ports:
    - protocol: TCP
      port: 4440
      targetPort: 4440
      nodePort: 30000

